version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'docker-app'
        container_name: app
        restart: unless-stopped
        volumes:
            - ./:/var/www

    webserver:
        build:
            context: .
            dockerfile: Dockerfile_Nginx
        image: nginx
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        depends_on:
            - app

    db:
        image: mysql:8
        container_name: db
        environment:
            MYSQL_DATABASE: sandbox
            MYSQL_ROOT_PASSWORD: rootadmin
        ports:
            - '3607:3606'
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
        driver: local